In [ ]:
import numpy as np
import math
np.set_printoptions(precision = 3, suppress = True)

In [ ]:
# 각 축별 변환행렬 정의

def trans_axis(theta, axis, par_x, par_y, par_z):

  s = math.sin(np.deg2rad(theta))
  c = math.cos(np.deg2rad(theta))

  matrix = [[0 for j in range(4)] for i in range(4)]
  matrix[0][3] = par_x
  matrix[1][3] = par_y
  matrix[2][3] = par_z
  matrix[3][3] = 1

  if axis == 'x':
    matrix[0][0] = 1
    matrix[1][1] = c
    matrix[2][1] = s
    matrix[1][2] = -s
    matrix[2][2] = c

  if axis == 'y':
    matrix[0][0] = c
    matrix[2][0] = -s
    matrix[1][1] = 1
    matrix[0][2] = s
    matrix[2][2] = c

  if axis == 'z':
    matrix[0][0] = c
    matrix[0][1] = -s
    matrix[1][0] = s
    matrix[1][1] = c
    matrix[2][2] = 1

  return matrix

In [ ]:
# 변환행렬로부터 Rx, Ry, Rz 추출

def find_angle(matrix):

  rot_angle = [0, 0, 0]

  rot_angle[0] = np.rad2deg(math.atan2(matrix[2][1], matrix[2][2]))
  rot_angle[1] = np.rad2deg(math.atan2(-matrix[2][0], math.sqrt(pow(matrix[0][0], 2) + pow(matrix[1][0], 2))))
  rot_angle[2] = np.rad2deg(math.atan2(matrix[1][0], matrix[0][0]))

  return rot_angle

In [ ]:
# 알짜 변환행렬 Tnet 추출

def find_Tnet(angle):
  T1 = trans_axis(angle[0]-90, 'z', 0, 0, 0)
  T2 = trans_axis(angle[1]-90, 'x', 0, 250, 460)
  T3 = trans_axis(angle[2], 'x', 0, 0, 700)
  T4 = trans_axis(angle[3], 'y', 0, -250, 150)
  T5 = trans_axis(angle[4], 'x', 0, 1050, 0)
  Rz = trans_axis(90, 'z', 0, 0, 0)
  Ry = trans_axis(90, 'y', 0, 0, 0)
  T6 = trans_axis(angle[5], 'z', 0, 0, 110)

  Tnet = np.dot(np.dot(np.dot(np.dot(np.dot(np.dot(np.dot(T1, T2), T3), T4), T5), Rz), Ry), T6)

  return Tnet

In [ ]:
aa = [0, 0, 0, 0, 0, 0]

aa[0], aa[1], aa[2], aa[3], aa[4], aa[5] = map(float, input('축별 각도를 입력하시오: ').split())

축별 각도를 입력하시오: 139.0 126.1 38.5 -20.2 81.9 125.4


In [ ]:
T = find_Tnet(aa)

xyz = np.dot(T, [0, 0, 0, 1])
Rxyz = find_angle(find_Tnet(aa))

print(T, "\n")

print('x =', xyz[0])
print('y =', xyz[1])
print('z =', xyz[2])
print('Rx =', Rxyz[0])
print('Ry =', Rxyz[1])
print('Rz =', Rxyz[2])

[[  -0.554    0.716    0.424  117.989]
 [  -0.569    0.045   -0.821 -152.392]
 [  -0.607   -0.696    0.383 1878.786]
 [   0.       0.       0.       1.   ]] 

x = 117.98914948826948
y = -152.39202246252506
z = 1878.786290776409
Rx = -61.212913108987486
Ry = 37.39545361034904
Rz = -134.2621551584979
